# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - icompressor

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://utilitymarketplace.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_5a535193dfd949fa835410592dff77fc }}
        password: ${{ secrets.AzureAppService_ContainerPassword_aa589279945f4b4e84decc80b21dd2cd }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: utilitymarketplace.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_5a535193dfd949fa835410592dff77fc }}/imgcompressor:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'icompressor'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_e8f3e73ad7714d22be18a16dc50213c7 }}
        images: 'utilitymarketplace.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_5a535193dfd949fa835410592dff77fc }}/imgcompressor:${{ github.sha }}'